linters:
  enable:
    - bodyclose
    - contextcheck
    # - depguard
    - durationcheck
    - dupl
    - errchkjson
    - errname
    - exhaustive
    - copyloopvar
    - gofmt
    - goimports
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - prealloc
    # - revive
    # - rowserrcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    # - wastedassign
    - whitespace
